### ISSUE TITLE
null pointer crash in factomexplorer 'search' handler (transient, recovered)

### ISSUE THREAD

**Issue by sugruedes** [FactomProject/WorkItems#156] opened 2015-01-30 17:07 UTC
Using factomexplorer, added chain and entries, then used search function to lookup chain id. One of the searches crashed a ha ndler with the following output to term:

2015/01/30 16:57:58 Handler crashed with error runtime error: invalid memory address or nil pointer dereference
2015/01/30 16:57:58 /usr/local/go/src/runtime/asm_amd64.s 401
2015/01/30 16:57:58 /usr/local/go/src/runtime/panic.go 387
2015/01/30 16:57:58 /usr/local/go/src/runtime/panic.go 42
2015/01/30 16:57:58 /usr/local/go/src/runtime/sigpanic_unix.go 26
2015/01/30 16:57:58 /home/des/factom/src/github.com/FactomProject/FactomCode/database/ldb/dblock.go 221
2015/01/30 16:57:58 /home/des/factom/src/github.com/FactomProject/factomexplorer/serve.go 938
2015/01/30 16:57:58 /home/des/factom/src/github.com/FactomProject/factomexplorer/serve.go 1041
2015/01/30 16:57:58 /usr/local/go/src/runtime/asm_amd64.s 401
2015/01/30 16:57:58 /usr/local/go/src/reflect/value.go 419
2015/01/30 16:57:58 /usr/local/go/src/reflect/value.go 296
2015/01/30 16:57:58 /home/des/factom/src/github.com/hoisie/web/server.go 216
2015/01/30 16:57:58 /home/des/factom/src/github.com/hoisie/web/server.go 361
2015/01/30 16:57:58 /home/des/factom/src/github.com/hoisie/web/server.go 94
2015/01/30 16:57:58 /home/des/factom/src/github.com/hoisie/web/server.go 89
2015/01/30 16:57:58 /usr/local/go/src/net/http/server.go 1541
2015/01/30 16:57:58 /usr/local/go/src/net/http/server.go 1703
2015/01/30 16:57:58 /usr/local/go/src/net/http/server.go 1204
2015/01/30 16:57:58 /usr/local/go/src/runtime/asm_amd64.s 2232
2015/01/30 16:57:58 127.0.0.1 -  POST /search - 529.482µs - Params: map[inputhash:a462f267c506521a684857e0fb2d575597f60fea2196f0801235e7811a519f59 hashtype:dblock]

No core file, parent process still running, process recovered.

**Comment by carryforward** [comment] 2015-01-31 00:18
Hi Des:

do you think you can reproduce this problem?  if you switch from the demo.factom.org server to a local one without deleting /tmp files then all kinds of crazyness happens.  the paths to clear are /tmp/client and /tmp/factomclient/

resetting restapi is also possible, and will happen on each reboot.  Deleting folders /tmp/ldb9/ and /tmp/wallet/ should reset restapi.

Although we are completely jumbling up restapi and factomclient, not much change is happening on factomexplorer right now.  if you find something to submit in that project, it is safe to make a pull request.

**Comment by sugruedes** [comment] 2015-01-31 12:29
In dblock.go, if db.lDb.Get() returns null, dBlock isnt instantiated. But its deferenced anyway in line 221.

**Comment by carryforward** [comment] 2015-02-03 01:16
Oh, great!  you did the hard part of finding where the bug is.  It looks like we aren't currently butchering this code.  would you mind making a pull request to the development branch?

**Comment by sugruedes** [comment] 2015-02-03 09:46
Im still getting up to speed on Go, so dont expect anything buildable for a while!  I will review the existing data access code for other similar issues and roll any fixes into a single branch for review.

**Comment by jaybny** [comment] 2015-02-03 17:59
i can fix crash, but still think there is a bug, code seems to be expecting data

**Comment by jaybny** [comment] 2015-02-03 18:03
fixed: https://github.com/FactomProject/FactomCode/commit/d14161bc37d3902d7f84de160061e7078a2d43a0

**Comment by carryforward** [comment] 2015-02-04 00:37
fixed by https://github.com/FactomProject/FactomCode/commit/d14161bc37d3902d7f84de160061e7078a2d43a0?diff=split

thanks Des.

**Closed by carryforward** 2015-02-04 00:37 UTC
